name: Tests

on:
  push:
    branches:
      - github_workflow_wip
  pull_request:
    branches:
      - github_workflow_wip

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        ios: ['17.2', '16.4'] # List all iOS versions installed for this Xcode

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.4'

      - name: Run tests on iOS ${{ matrix.ios }}
        run: |
          set -o pipefail
          xcodebuild test \
            -scheme PopNetworking \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=${{ matrix.ios }}' \
            | xcpretty
  # macOS:
  #   runs-on: macos-15
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Xcode
  #       uses: maxim-lobanov/setup-xcode@v1.6.0
  #       with:
  #         xcode-version: '16.4'
  
  #     - name: Run tests
  #       run: swift test

  # iOS:
  #   runs-on: macos-15
  #   steps:
  #     - uses: actions/checkout@v4
  
  #     - name: Setup Xcode
  #       uses: maxim-lobanov/setup-xcode@v1.6.0
  #       with:
  #         xcode-version: '16.4'

  #     - name: Run tests on iOS Simulator
  #       run: |
  #         set -o pipefail
  #         xcodebuild test \
  #           -scheme PopNetworking \
  #           -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
  #           | xcpretty

  # watchOS:
  #   runs-on: macos-15
  #   steps:
  #     - uses: actions/checkout@v4
  
  #     - name: Setup Xcode
  #       uses: maxim-lobanov/setup-xcode@v1.6.0
  #       with:
  #         xcode-version: '16.4'

  #     - name: Run tests on watchOS Simulator
  #       run: |
  #         set -o pipefail
  #         xcodebuild test \
  #           -scheme PopNetworking \
  #           -destination 'platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm),OS=11.2' \
  #           | xcpretty

  # tvOS:
  #   runs-on: macos-15
  #   steps:
  #     - uses: actions/checkout@v4
  
  #     - name: Setup Xcode
  #       uses: maxim-lobanov/setup-xcode@v1.6.0
  #       with:
  #         xcode-version: '16.4'

  #     - name: Run tests on tvOS Simulator
  #       run: |
  #         set -o pipefail
  #         xcodebuild test \
  #           -scheme PopNetworking \
  #           -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=18.2' \
  #           | xcpretty

  # visionOS:
  #   runs-on: macos-15
  #   steps:
  #     - uses: actions/checkout@v4
    
  #     - name: Setup Xcode
  #       uses: maxim-lobanov/setup-xcode@v1.6.0
  #       with:
  #         xcode-version: '16.4'

  #     - name: Run tests on visionOS Simulator
  #       run: |
  #         set -o pipefail
  #         xcodebuild test \
  #           -scheme PopNetworking \
  #           -destination 'platform=visionOS Simulator,name=Apple Vision Pro,OS=2.2' \
  #           | xcpretty
